name: PHP Student Project CI

on:
  push:
    branches: [ main, master ] # сработает при пуше в эти ветки

jobs:
  # ЭТАП 1: Сборка
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker images
        run: docker compose build php

  # ЭТАП 2: Тестирование (Разделение pipeline — штрафное задание)
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start services
        run: docker compose up -d

      - name: Wait for services (Штрафное задание)
        run: sleep 15 # Ждем поднятия MySQL и Kafka

      - name: Check containers (Штрафное задание)
        run: docker ps

      - name: Install dependencies
        run: docker compose exec -T php composer install

      - name: Run PHPUnit Tests
        run: docker compose exec -T php vendor/bin/phpunit tests

      - name: Show logs on error (Штрафное задание)
        if: failure() # Выполнится только если тесты упали
        run: docker compose logs

      - name: Stop containers
        if: always()
        run: docker compose down