name: PHP Student Project CI

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker images
        # Мы указываем Docker зайти в папку 9 лабы и собрать образ там
        run: docker compose -f 9_kyu_web_lab/docker-compose.yml build lab7_php

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start services
        run: docker compose -f 9_kyu_web_lab/docker-compose.yml up -d

      - name: Wait for MySQL
        run: sleep 15

      - name: Install dependencies
        # Выполняем установку внутри контейнера, используя конфиг из папки
        run: docker compose -f 9_kyu_web_lab/docker-compose.yml exec -T lab7_php composer install

      - name: Run PHPUnit Tests
        # Важно: указываем путь к тестам внутри контейнера
        run: docker compose -f 9_kyu_web_lab/docker-compose.yml exec -T lab7_php vendor/bin/phpunit 9_kyu_web_lab/tests

      - name: Show logs on error
        if: failure()
        run: docker compose -f 9_kyu_web_lab/docker-compose.yml logs

      - name: Stop containers
        if: always()
        run: docker compose -f 9_kyu_web_lab/docker-compose.yml down